---
- name: Check if updates available on Mikrotik
  hosts: all
  tasks:
    - name: Check if new update available
      raw: system package update check-for-updates
      register: mikrotik_output

    - name: Print output
      debug: msg= {{ mikrotik_output.stdout_lines }}