---
- hosts: all
  gather_facts: False
  tasks:
    - name: Sending an e-mail using AWS SES
      community.general.mail:
        host: "{{ smtp.host }}"
        port: 587
        username: "{{ smtp.username }}"
        password: "{{ smtp.password }}"
        to: "{{ smtp.to_user }}"
        subject: Ansible-report
        body: System has been successfully provisioned.
      delegate_to: localhost
