---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
    - name: Sending an e-mail using AWS SES
      community.general.mail:
        host: "{{ smtp_host }}"
        port: 587
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ smtp_to_user }}"
        subject: Ansible-report
        body: System has been successfully provisioned.
        sender: "{{ smtp_sender }}"
